---
title: "main"
format: pdf
editor: visual
---

## 

```{r}
library(readxl)
library(rpart)
library(rpart.plot)

file <- "/Users/ny/COSC 3337/Predicting_Heart_Disease/heart-disease2.xlsx"
data <- read_excel(file)
```

```{r}
set.seed(123)

split <- sample.split(data$target, SplitRatio = 0.8)
train_data <- subset(data, split == TRUE)
test_data <- subset(data, split == FALSE)
```

```{r}
tree_depth_3 <- rpart(target ~ ., data = train_data, method = "class", control = rpart.control(maxdepth = 3))
predictions_depth_3 <- predict(tree_depth_3, test_data, type = "class")
tree_depth_7 <- rpart(target ~ ., data = train_data, method = "class", control = rpart.control(maxdepth = 7))
predictions_depth_7 <- predict(tree_depth_7, test_data, type = "class")
tree_depth_11 <- rpart(target ~ ., data = train_data, method = "class", control = rpart.control(maxdepth = 11))
predictions_depth_11 <- predict(tree_depth_11, test_data, type = "class")
tree_depth_15 <- rpart(target ~ ., data = train_data, method = "class", control = rpart.control(maxdepth = 15))
predictions_depth_15 <- predict(tree_depth_15, test_data, type = "class")
```
